### ISSUE TITLE
Stuck while starting AEM (Step 4)

### ISSUE THREAD

**Issue by harshkotak** [remcorakers/aem-docker-getting-started#3]
Stuck with the AEM startup output

Loading quickstart properties: default
Loading quickstart properties: instance
Low-memory action set to fork
Using 64bit VM settings, min.heap=1024MB, min permgen=256MB, default fork arguments=[-Xmx1024m, -XX:MaxPermSize=256m]
The JVM reports a heap size of 7851 MB, meets our expectation of 1024 MB +/- 20
No console, will fork to get enough memory
Not forking JVM as -nofork option is set
Setting properties from filename '/opt/aem/AEM_6.x_Quickstart.jar'
Setting 'sling.run.modes' to 'publish,nosamplecontent,local' from command line.
Unable to setup Swing UI, will use system console only (java.awt.HeadlessException)
Verbose option not active, closing stdin and redirecting stdout and stderr
Redirecting stdout to /opt/aem/crx-quickstart/logs/stdout.log
Redirecting stderr to /opt/aem/crx-quickstart/logs/stderr.log
Press CTRL-C to shutdown the Quickstart server...

@remcorakers  @sveneh  - Can you help. Have you come across this before?

**Comment by remcorakers** [comment]
@harshkotak This error doesn't sound familiar to me. What version of AEM are you using? Is there any info available in the logs of the author, dispatcher or publisher?
